# Generated by Django 5.2.16 on 2026-08-01 10:18

import common.upload
import common.validators
import lost_found.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostFoundItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], max_length=10)),
                ('category', models.CharField(choices=[('id_card', 'ID Card'), ('wallet', 'Wallet'), ('gadget', 'Gadget'), ('book', 'Book'), ('clothing', 'Clothing'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=common.upload.UploadToPath('lost_found'), validators=[common.validators.validate_image])),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('open', 'Open'), ('matched', 'Matched'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=10)),
                ('tracking_code', models.CharField(default=lost_found.models._generate_tracking_code, editable=False, max_length=12, unique=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['item_type', 'status'], name='lost_found__item_ty_bf8540_idx'), models.Index(fields=['-created_at'], name='lost_found__created_edfddf_idx')],
            },
        ),
    ]
