# Generated by Django 5.2.16 on 2026-08-01 10:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('suggestion', 'Suggestion'), ('compliment', 'Compliment'), ('concern', 'Concern'), ('shoutout', 'Shoutout')], default='suggestion', max_length=20)),
                ('content', models.TextField()),
                ('name', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'status'], name='student_voi_categor_27deb6_idx'), models.Index(fields=['-created_at'], name='student_voi_created_9c8e81_idx')],
            },
        ),
    ]
