# Generated by Django 5.2.16 on 2026-08-01 10:14

import common.upload
import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=common.upload.UploadToPath('ebooks/covers'), validators=[common.validators.validate_image])),
                ('file', models.FileField(upload_to=common.upload.UploadToPath('ebooks/files'), validators=[common.validators.validate_pdf])),
                ('category', models.CharField(choices=[('textbook', 'Textbook'), ('module', 'Module'), ('reference', 'Reference'), ('syllabus', 'Syllabus')], default='textbook', max_length=20)),
                ('pages', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='ebooks_book_categor_b6f635_idx'), models.Index(fields=['-created_at'], name='ebooks_book_created_59c226_idx')],
            },
        ),
    ]
