# Generated by Django 5.2.17 on 2026-08-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ebooks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="course",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BSCpE", "BSCpE"),
                    ("BSCE", "BSCE"),
                    ("BSARCHI", "BSARCHI"),
                    ("BSECE", "BSECE"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="year_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1st", "1st Year"),
                    ("2nd", "2nd Year"),
                    ("3rd", "3rd Year"),
                    ("4th", "4th Year"),
                    ("5th", "5th Year"),
                ],
                default="",
                max_length=10,
            ),
        ),
    ]
