# Generated by Django 5.2.16 on 2026-08-01 10:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('floorplans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(choices=[('classroom', 'Classroom'), ('laboratory', 'Laboratory'), ('office', 'Office'), ('service', 'Service'), ('entrance', 'Entrance'), ('restroom', 'Restroom'), ('other', 'Other')], default='other', max_length=20)),
                ('floor', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='floorplans.building')),
            ],
            options={
                'ordering': ['building__order', 'building__name', 'floor', 'name'],
                'indexes': [models.Index(fields=['building', 'category'], name='wayfinding__buildin_568a48_idx'), models.Index(fields=['is_active'], name='wayfinding__is_acti_87072b_idx')],
            },
        ),
    ]
